name: CI
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: experimental-features = nix-command flakes

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake
        run: nix flake check

      - name: Format check
        run: |
          nix develop --command alejandra --check .

      - name: Lint
        run: |
          nix develop --command statix check .
          nix develop --command deadnix --fail .

      - name: Build NixOS config
        run: |
          nix build .#nixosConfigurations.thinkpad.config.system.build.toplevel

      - name: Build home-manager config
        run: |
          nix build .#homeConfigurations.louis.activationPackage
